image: adoptopenjdk/openjdk14:jdk-14.0.2_12

stages:
  - build
  - validate
  - test
  - release

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

server-build:
  stage: build
  script:
    ./gradlew --build-cache :server:assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build/
      - .gradle/

server-checkstyle:
  stage: validate
  script: ./gradlew :server:checkstyleMain :server:checkstyleTest
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build/
      - .gradle/
  allow_failure: true

server-test:
  stage: test
  script:
    - ./gradlew :server:test :server:jacocoTestReport
    - cat server/build/reports/jacoco/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/

server-release:
  allow_failure: true
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo 'running release_job'
    - ./gradlew :server:distTar :server:distZip :server:bootJar
  cache:
    paths:
      - build/
      - .gradle/
  artifacts:
    paths:
      - server/build/distributions/server.zip
      - server/build/distributions/server.tar
      - server/build/libs/server.jar